export const FIND_PHOTO = 'FIND_PHOTO';
export const FIND_PROFILE = 'FIND_PROFILE';
export const FIND_GALLERYITEMS = 'FIND_GALLERYITEMS';
export const FIND_RANDOMPHOTO = 'FIND_RANDOMPHOTO';
export const TOGGLE_MENUSHOW = 'TOGGLE_MENUSHOW';
export const SORT_MOSTLIKES = 'SORT_MOSTLIKES';
export const SORT_FEWESTLIKES = 'SORT_FEWESTLIKES';

export const CHANGE_LOADING_STATUS = 'CHANGE_LOADING_STATUS';